// Package config reads and writes kube-ctx's own configuration file, which
// holds context aliases and the guard rules that classify a context as
// production.
//
// The file is optional. A missing or empty config yields built-in defaults, so
// kube-ctx works on a fresh machine with nothing set up.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/somaz94/kube-ctx/pkg/paths"
)

// FileName is the config file's basename inside the kube-ctx config directory.
const FileName = "config.yaml"

// filePerm keeps the config owner-only, consistent with everything else
// kube-ctx writes.
const filePerm = 0o600

// header is written above the marshalled config.
//
// The guard defaults label but never block, which is the right default but an
// invisible one: without this, the only way to learn that confirm exists is to
// read the docs. Save() writes the rules out explicitly, so the line to change
// is already in the file — this says what changing it does.
//
// It is regenerated on every Save because yaml.Marshal cannot round-trip
// comments; anything the user writes between the keys is lost either way.
const header = `# kube-ctx configuration.
#
# guards classify a context by name; the first matching rule wins. By default
# they only label and colorize — switching is never blocked. Set confirm: true
# on a rule to require retyping the exact context name before switching to a
# context it matches (kctx -y skips the prompt, for scripts).
#
# A rule carries exactly one matcher: match (regex), contexts (exact names),
# prefix, or suffix. Manage them with kctx guard.
#
# aliases are accepted anywhere a context name is; manage them with kctx alias.
#
# Regenerated by kctx alias and kctx guard — comments added below this block
# are not kept.

`

// Level is how dangerous a context is considered.
type Level string

const (
	// LevelSafe is the default for anything no guard rule matches.
	LevelSafe Level = "safe"
	// LevelWarn marks a context worth a visible reminder.
	LevelWarn Level = "warn"
	// LevelDanger marks production.
	LevelDanger Level = "danger"
)

// Guard classifies contexts by name.
//
// A rule carries exactly one matcher. Match is the general one; Contexts,
// Prefix and Suffix exist because the names that most need guarding are the
// ones a regex over "prod" never catches — the cluster called cluster-7 that
// happens to run the business — and demanding a regex to name it is a barrier
// in front of the safety feature.
type Guard struct {
	// Match is a regular expression tested against the context name.
	Match string `yaml:"match,omitempty" json:"match,omitempty"`
	// Contexts is an exact list of context names this rule applies to.
	Contexts []string `yaml:"contexts,omitempty" json:"contexts,omitempty"`
	// Prefix matches context names that start with it.
	Prefix string `yaml:"prefix,omitempty" json:"prefix,omitempty"`
	// Suffix matches context names that end with it.
	Suffix string `yaml:"suffix,omitempty" json:"suffix,omitempty"`
	// Level is safe, warn, or danger.
	Level Level `yaml:"level" json:"level"`
	// Confirm requires the user to retype the context name before switching.
	Confirm bool `yaml:"confirm" json:"confirm"`
	// Label overrides the badge text shown next to a matching context.
	Label string `yaml:"label,omitempty" json:"label,omitempty"`
}

// Matchers returns the names of the matcher fields this rule sets.
//
// Reported rather than resolved by precedence: two matchers on one rule is a
// typo, and silently honouring one of them is how a context nobody guarded
// ends up looking guarded.
func (g Guard) Matchers() []string {
	var set []string
	if g.Match != "" {
		set = append(set, "match")
	}
	if len(g.Contexts) > 0 {
		set = append(set, "contexts")
	}
	if g.Prefix != "" {
		set = append(set, "prefix")
	}
	if g.Suffix != "" {
		set = append(set, "suffix")
	}
	return set
}

// Describe renders the rule's matcher for display.
func (g Guard) Describe() string {
	switch {
	case len(g.Contexts) > 0:
		return strings.Join(g.Contexts, ", ")
	case g.Prefix != "":
		return g.Prefix + "*"
	case g.Suffix != "":
		return "*" + g.Suffix
	default:
		return g.Match
	}
}

// Config is the whole kube-ctx configuration file.
type Config struct {
	// Aliases maps a short name to a context name.
	Aliases map[string]string `yaml:"aliases,omitempty"`
	// Guards classify contexts. The first matching rule wins.
	Guards []Guard `yaml:"guards,omitempty"`

	// path is where this config was loaded from, so Save round-trips.
	path string
	// configuredGuards records whether Guards came from the file, which is
	// otherwise unrecoverable once the defaults have been substituted in.
	configuredGuards bool
}

// DefaultGuards is used when the config file defines none. It only colors and
// labels — Confirm is off — so a first run never blocks on a prompt the user
// did not ask for. Enabling confirm is a one-line edit documented in the
// generated config.
func DefaultGuards() []Guard {
	return []Guard{
		{Match: `(^|[-_.])(prod|prd|production)([-_.]|$)`, Level: LevelDanger},
		{Match: `(^|[-_.])(stg|stage|staging|uat)([-_.]|$)`, Level: LevelWarn},
	}
}

// Path returns the default config file location.
func Path() (string, error) {
	dir, err := paths.ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, FileName), nil
}

// Load reads the config from its default location.
func Load() (*Config, error) {
	path, err := Path()
	if err != nil {
		return nil, err
	}
	return LoadFrom(path)
}

// LoadFrom reads the config from path. A missing file is not an error: it
// yields a config with the default guards and no aliases.
func LoadFrom(path string) (*Config, error) {
	cfg := &Config{path: path}

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		cfg.Guards = DefaultGuards()
		return cfg, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read config %s: %w", path, err)
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config %s: %w", path, err)
	}
	cfg.configuredGuards = len(cfg.Guards) > 0
	if len(cfg.Guards) == 0 {
		cfg.Guards = DefaultGuards()
	}
	return cfg, nil
}

// HasGuards reports whether the guard rules came from the config file rather
// than from the built-in defaults. Callers use it to say so, since the two are
// indistinguishable once loaded.
func (c *Config) HasGuards() bool { return c.configuredGuards }

// AddGuard prepends a rule, so it is consulted before the ones already there.
//
// Prepending is what makes "kctx guard add cluster-7 --confirm" do what it
// looks like it does: a rule appended after the built-in patterns would lose
// to them for any name that also happens to contain "prod".
func (c *Config) AddGuard(g Guard) {
	if len(c.Guards) == 0 {
		c.Guards = DefaultGuards()
	}
	c.Guards = append([]Guard{g}, c.Guards...)
	c.configuredGuards = true
}

// RemoveGuard deletes the rule at the given 1-based position and returns it.
func (c *Config) RemoveGuard(position string) (Guard, error) {
	if len(c.Guards) == 0 {
		c.Guards = DefaultGuards()
	}

	n, err := strconv.Atoi(strings.TrimSpace(position))
	if err != nil {
		return Guard{}, fmt.Errorf("guard %q is not a number; see \"kctx guard list\"", position)
	}
	if n < 1 || n > len(c.Guards) {
		return Guard{}, fmt.Errorf("no guard %d; there are %d", n, len(c.Guards))
	}

	removed := c.Guards[n-1]
	c.Guards = append(c.Guards[:n-1:n-1], c.Guards[n:]...)
	c.configuredGuards = true
	return removed, nil
}

// Path returns where this config lives on disk.
func (c *Config) Path() string { return c.path }

// Save writes the config back, creating the directory if needed.
func (c *Config) Save() error {
	if c.path == "" {
		path, err := Path()
		if err != nil {
			return err
		}
		c.path = path
	}
	if err := paths.EnsureDir(filepath.Dir(c.path)); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("encode config: %w", err)
	}
	if err := os.WriteFile(c.path, append([]byte(header), data...), filePerm); err != nil {
		return fmt.Errorf("write config %s: %w", c.path, err)
	}
	return nil
}

// ResolveAlias maps an alias to its context name, returning name unchanged when
// it is not an alias. A leading "@" is accepted so users can force the alias
// reading of a name that also exists as a context.
func (c *Config) ResolveAlias(name string) string {
	explicit := strings.HasPrefix(name, "@")
	key := strings.TrimPrefix(name, "@")

	if target, ok := c.Aliases[key]; ok {
		return target
	}
	if explicit {
		return key
	}
	return name
}

// SetAlias records an alias.
func (c *Config) SetAlias(alias, target string) error {
	alias = strings.TrimPrefix(alias, "@")
	if alias == "" {
		return fmt.Errorf("the alias must not be empty")
	}
	if target == "" {
		return fmt.Errorf("the target context must not be empty")
	}
	if c.Aliases == nil {
		c.Aliases = map[string]string{}
	}
	c.Aliases[alias] = target
	return nil
}

// DeleteAlias removes an alias.
func (c *Config) DeleteAlias(alias string) error {
	alias = strings.TrimPrefix(alias, "@")
	if _, ok := c.Aliases[alias]; !ok {
		return fmt.Errorf("no alias named %q", alias)
	}
	delete(c.Aliases, alias)
	return nil
}

// AliasPair is one alias-to-context mapping.
type AliasPair struct {
	Alias  string `json:"alias" yaml:"alias"`
	Target string `json:"target" yaml:"target"`
}

// AliasList returns every alias sorted by name.
func (c *Config) AliasList() []AliasPair {
	out := make([]AliasPair, 0, len(c.Aliases))
	for alias, target := range c.Aliases {
		out = append(out, AliasPair{Alias: alias, Target: target})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Alias < out[j].Alias })
	return out
}
