// Package config reads and writes kube-ctx's own configuration file, which
// holds context aliases and the guard rules that classify a context as
// production.
//
// The file is optional. A missing or empty config yields built-in defaults, so
// kube-ctx works on a fresh machine with nothing set up.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/somaz94/kube-ctx/pkg/paths"
)

// FileName is the config file's basename inside the kube-ctx config directory.
const FileName = "config.yaml"

// filePerm keeps the config owner-only, consistent with everything else
// kube-ctx writes.
const filePerm = 0o600

// header is written above the marshalled config.
//
// The guard defaults label but never block, which is the right default but an
// invisible one: without this, the only way to learn that confirm exists is to
// read the docs. Save() writes the rules out explicitly, so the line to change
// is already in the file — this says what changing it does.
//
// It is regenerated on every Save because yaml.Marshal cannot round-trip
// comments; anything the user writes between the keys is lost either way.
const header = `# kube-ctx configuration.
#
# guards classify a context by name; the first matching rule wins. By default
# they only label and colorize — switching is never blocked. Set confirm: true
# on a rule to require retyping the exact context name before switching to a
# context it matches (kctx -y skips the prompt, for scripts).
#
# A rule carries exactly one matcher: match (regex), contexts (exact names),
# prefix, or suffix. Manage them with kctx guard.
#
# A rule that also lists namespaces classifies those namespaces inside the
# contexts it matches, instead of the contexts themselves — so kube-system in
# production can require confirming while switching to production does not.
# The context matcher may then be left out, meaning every context. Namespace
# rules gate kctx ns, kctx exec -n and kctx shell -n alike.
#
# aliases are accepted anywhere a context name is; manage them with kctx alias.
#
# bindings map a directory to the context to work in there. With the shell hook
# installed, entering one switches this terminal to it; manage them with
# kctx bind.
#
# Regenerated by kctx alias, kctx guard and kctx bind — comments added below
# this block are not kept.

`

// Level is how dangerous a context is considered.
type Level string

const (
	// LevelSafe is the default for anything no guard rule matches.
	LevelSafe Level = "safe"
	// LevelWarn marks a context worth a visible reminder.
	LevelWarn Level = "warn"
	// LevelDanger marks production.
	LevelDanger Level = "danger"
)

// Guard classifies contexts by name.
//
// A rule carries exactly one matcher. Match is the general one; Contexts,
// Prefix and Suffix exist because the names that most need guarding are the
// ones a regex over "prod" never catches — the cluster called cluster-7 that
// happens to run the business — and demanding a regex to name it is a barrier
// in front of the safety feature.
type Guard struct {
	// Match is a regular expression tested against the context name.
	Match string `yaml:"match,omitempty" json:"match,omitempty"`
	// Contexts is an exact list of context names this rule applies to.
	Contexts []string `yaml:"contexts,omitempty" json:"contexts,omitempty"`
	// Prefix matches context names that start with it.
	Prefix string `yaml:"prefix,omitempty" json:"prefix,omitempty"`
	// Suffix matches context names that end with it.
	Suffix string `yaml:"suffix,omitempty" json:"suffix,omitempty"`
	// Namespaces narrows the rule to these exact namespaces inside a matching
	// context, turning it from a rule about a cluster into a rule about a
	// place within one.
	//
	// Setting it moves the whole rule onto the namespace axis: it stops
	// classifying the context itself. Switching to a cluster and moving around
	// inside it are different acts and want different verdicts — a context
	// worth badging is rarely one worth prompting for, while kube-system is
	// the reverse — and one rule cannot carry both, since Level, Confirm and
	// Label would have to mean two things at once. Guard both by writing two
	// rules.
	//
	// Exact names, not a pattern: unlike context names, the namespaces worth
	// guarding are the standard ones every cluster spells identically.
	Namespaces []string `yaml:"namespaces,omitempty" json:"namespaces,omitempty"`
	// Level is safe, warn, or danger.
	Level Level `yaml:"level" json:"level"`
	// Confirm requires the user to retype the context name before switching.
	Confirm bool `yaml:"confirm" json:"confirm"`
	// Label overrides the badge text shown next to a matching context.
	Label string `yaml:"label,omitempty" json:"label,omitempty"`
}

// Matchers returns the names of the matcher fields this rule sets.
//
// Reported rather than resolved by precedence: two matchers on one rule is a
// typo, and silently honouring one of them is how a context nobody guarded
// ends up looking guarded.
func (g Guard) Matchers() []string {
	var set []string
	if g.Match != "" {
		set = append(set, "match")
	}
	if len(g.Contexts) > 0 {
		set = append(set, "contexts")
	}
	if g.Prefix != "" {
		set = append(set, "prefix")
	}
	if g.Suffix != "" {
		set = append(set, "suffix")
	}
	return set
}

// ScopesNamespaces reports whether this rule classifies namespaces inside the
// contexts it matches, rather than the contexts themselves.
func (g Guard) ScopesNamespaces() bool { return len(g.Namespaces) > 0 }

// Describe renders the rule's matcher for display.
//
// A namespace rule is rendered as both halves, "prod-* / kube-system", because
// the two axes share one list: told only "kube-system", the reader cannot see
// whether the rule reaches the cluster in front of them.
func (g Guard) Describe() string {
	if !g.ScopesNamespaces() {
		return g.describeContexts()
	}
	where := g.describeContexts()
	if where == "" {
		// No context matcher is legal here and means every context, which has
		// to be said out loud: an unqualified "kube-system" reads as a rule
		// somebody forgot to finish.
		where = "any context"
	}
	return where + " / " + strings.Join(g.Namespaces, ", ")
}

// describeContexts renders the context half of the matcher, empty when the
// rule sets none.
func (g Guard) describeContexts() string {
	switch {
	case len(g.Contexts) > 0:
		return strings.Join(g.Contexts, ", ")
	case g.Prefix != "":
		return g.Prefix + "*"
	case g.Suffix != "":
		return "*" + g.Suffix
	default:
		return g.Match
	}
}

// Config is the whole kube-ctx configuration file.
type Config struct {
	// Aliases maps a short name to a context name.
	Aliases map[string]string `yaml:"aliases,omitempty"`
	// Guards classify contexts. The first matching rule wins.
	Guards []Guard `yaml:"guards,omitempty"`
	// Bindings maps an absolute directory to the context to work in there.
	Bindings map[string]string `yaml:"bindings,omitempty"`

	// path is where this config was loaded from, so Save round-trips.
	path string
	// configuredGuards records whether Guards came from the file, which is
	// otherwise unrecoverable once the defaults have been substituted in.
	configuredGuards bool
}

// DefaultGuards is used when the config file defines none. It only colors and
// labels — Confirm is off — so a first run never blocks on a prompt the user
// did not ask for. Enabling confirm is a one-line edit documented in the
// generated config.
func DefaultGuards() []Guard {
	return []Guard{
		{Match: `(^|[-_.])(prod|prd|production)([-_.]|$)`, Level: LevelDanger},
		{Match: `(^|[-_.])(stg|stage|staging|uat)([-_.]|$)`, Level: LevelWarn},
	}
}

// Path returns the default config file location.
func Path() (string, error) {
	dir, err := paths.ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, FileName), nil
}

// Load reads the config from its default location.
func Load() (*Config, error) {
	path, err := Path()
	if err != nil {
		return nil, err
	}
	return LoadFrom(path)
}

// LoadFrom reads the config from path. A missing file is not an error: it
// yields a config with the default guards and no aliases.
func LoadFrom(path string) (*Config, error) {
	cfg := &Config{path: path}

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		cfg.Guards = DefaultGuards()
		return cfg, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read config %s: %w", path, err)
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse config %s: %w", path, err)
	}
	cfg.configuredGuards = len(cfg.Guards) > 0
	if len(cfg.Guards) == 0 {
		cfg.Guards = DefaultGuards()
	}
	return cfg, nil
}

// HasGuards reports whether the guard rules came from the config file rather
// than from the built-in defaults. Callers use it to say so, since the two are
// indistinguishable once loaded.
func (c *Config) HasGuards() bool { return c.configuredGuards }

// AddGuard prepends a rule, so it is consulted before the ones already there.
//
// Prepending is what makes "kctx guard add cluster-7 --confirm" do what it
// looks like it does: a rule appended after the built-in patterns would lose
// to them for any name that also happens to contain "prod".
func (c *Config) AddGuard(g Guard) {
	if len(c.Guards) == 0 {
		c.Guards = DefaultGuards()
	}
	c.Guards = append([]Guard{g}, c.Guards...)
	c.configuredGuards = true
}

// RemoveGuard deletes the rule at the given 1-based position and returns it.
func (c *Config) RemoveGuard(position string) (Guard, error) {
	if len(c.Guards) == 0 {
		c.Guards = DefaultGuards()
	}

	n, err := strconv.Atoi(strings.TrimSpace(position))
	if err != nil {
		return Guard{}, fmt.Errorf("guard %q is not a number; see \"kctx guard list\"", position)
	}
	if n < 1 || n > len(c.Guards) {
		return Guard{}, fmt.Errorf("no guard %d; there are %d", n, len(c.Guards))
	}

	removed := c.Guards[n-1]
	c.Guards = append(c.Guards[:n-1:n-1], c.Guards[n:]...)
	c.configuredGuards = true
	return removed, nil
}

// Path returns where this config lives on disk.
func (c *Config) Path() string { return c.path }

// Save writes the config back, creating the directory if needed.
func (c *Config) Save() error {
	if c.path == "" {
		path, err := Path()
		if err != nil {
			return err
		}
		c.path = path
	}
	if err := paths.EnsureDir(filepath.Dir(c.path)); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("encode config: %w", err)
	}
	if err := os.WriteFile(c.path, append([]byte(header), data...), filePerm); err != nil {
		return fmt.Errorf("write config %s: %w", c.path, err)
	}
	return nil
}

// ResolveAlias maps an alias to its context name, returning name unchanged when
// it is not an alias. A leading "@" is accepted so users can force the alias
// reading of a name that also exists as a context.
func (c *Config) ResolveAlias(name string) string {
	explicit := strings.HasPrefix(name, "@")
	key := strings.TrimPrefix(name, "@")

	if target, ok := c.Aliases[key]; ok {
		return target
	}
	if explicit {
		return key
	}
	return name
}

// SetAlias records an alias.
func (c *Config) SetAlias(alias, target string) error {
	alias = strings.TrimPrefix(alias, "@")
	if alias == "" {
		return fmt.Errorf("the alias must not be empty")
	}
	if target == "" {
		return fmt.Errorf("the target context must not be empty")
	}
	if c.Aliases == nil {
		c.Aliases = map[string]string{}
	}
	c.Aliases[alias] = target
	return nil
}

// DeleteAlias removes an alias.
func (c *Config) DeleteAlias(alias string) error {
	alias = strings.TrimPrefix(alias, "@")
	if _, ok := c.Aliases[alias]; !ok {
		return fmt.Errorf("no alias named %q", alias)
	}
	delete(c.Aliases, alias)
	return nil
}

// SetBinding records the context to work in under dir.
func (c *Config) SetBinding(dir, context string) error {
	dir, err := normalizeDir(dir)
	if err != nil {
		return err
	}
	if context == "" {
		return fmt.Errorf("the bound context must not be empty")
	}
	if c.Bindings == nil {
		c.Bindings = map[string]string{}
	}
	c.Bindings[dir] = context
	return nil
}

// DeleteBinding removes the binding recorded for exactly dir.
//
// Deliberately not the one it inherits: "kctx bind --delete" in a subdirectory
// of a bound repository should say there is nothing bound here, rather than
// silently unbinding the repository from underneath the rest of it.
func (c *Config) DeleteBinding(dir string) error {
	dir, err := normalizeDir(dir)
	if err != nil {
		return err
	}
	if _, ok := c.Bindings[dir]; !ok {
		return fmt.Errorf("no context is bound to %s", dir)
	}
	delete(c.Bindings, dir)
	return nil
}

// ResolveBinding returns the context bound to dir or to its nearest bound
// ancestor, and the directory that binding was recorded on.
//
// Nearest rather than first: a repository can bind its root to the shared
// cluster and one subdirectory to a different one, and the more specific
// binding has to win however the map happens to be ordered.
func (c *Config) ResolveBinding(dir string) (context, boundAt string, ok bool) {
	dir, err := normalizeDir(dir)
	if err != nil {
		return "", "", false
	}
	for candidate, target := range c.Bindings {
		if !underDir(dir, candidate) {
			continue
		}
		// Longer means deeper, since both are cleaned absolute paths.
		if len(candidate) > len(boundAt) || !ok {
			context, boundAt, ok = target, candidate, true
		}
	}
	return context, boundAt, ok
}

// underDir reports whether dir is parent or a directory inside it.
//
// The separator check is what keeps "/srv/apiary" from matching a binding on
// "/srv/api": a plain prefix test binds directories that merely start with the
// same letters.
func underDir(dir, parent string) bool {
	if dir == parent {
		return true
	}
	return strings.HasPrefix(dir, strings.TrimSuffix(parent, string(os.PathSeparator))+string(os.PathSeparator))
}

// normalizeDir turns a directory into the canonical form bindings are keyed by,
// so "." and a trailing slash name the same binding as the full path.
//
// Symlinks are resolved as well, and that part is load-bearing rather than
// tidiness: on macOS /tmp and /var are themselves symlinks, and a home
// directory or checkout reached through one is common everywhere. Binding the
// path the user typed and looking up the path the process reports would then
// never match. A directory that does not exist keeps its plain absolute form —
// binding one is unusual but not an error.
func normalizeDir(dir string) (string, error) {
	if strings.TrimSpace(dir) == "" {
		return "", fmt.Errorf("the bound directory must not be empty")
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolve directory %s: %w", dir, err)
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved, nil
	}
	return abs, nil
}

// BindingPair is one directory-to-context binding.
type BindingPair struct {
	Directory string `json:"directory" yaml:"directory"`
	Target    string `json:"target" yaml:"target"`
}

// BindingList returns every binding sorted by directory.
func (c *Config) BindingList() []BindingPair {
	out := make([]BindingPair, 0, len(c.Bindings))
	for dir, target := range c.Bindings {
		out = append(out, BindingPair{Directory: dir, Target: target})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Directory < out[j].Directory })
	return out
}

// AliasPair is one alias-to-context mapping.
type AliasPair struct {
	Alias  string `json:"alias" yaml:"alias"`
	Target string `json:"target" yaml:"target"`
}

// AliasList returns every alias sorted by name.
func (c *Config) AliasList() []AliasPair {
	out := make([]AliasPair, 0, len(c.Aliases))
	for alias, target := range c.Aliases {
		out = append(out, AliasPair{Alias: alias, Target: target})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Alias < out[j].Alias })
	return out
}
